# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: Simple Deploy
description: Deploy an project to a runtime server, trivially
author: Cameron Tacklind <cameron@tacklind.com>
inputs:
  deploy-key:
    required: true
    description: The key to use to auth with

  runtime-host-user:
    required: true
    description: User of the runtime server that we're deploying to
  runtime-host-hostname:
    required: true
    description: Hostname of the runtime server that we're deploying to
  runtime-host-port:
    required: false
    description: Port of the runtime server that we're deploying to

  runtime-host-directory:
    required: true
    description: The place to deploy to

  runtime-host-keys:
    required: false
    description: |
      The ssh fingerprint of the runtime server. Output of:
      $ ssh-keyscan your.server

  systemd-service:
    required: true
    description: The Systemd service to stop and start

  deploy-directory:
    required: false
    description: Folder to copy to remote
    default: '.' # Maybe dist?

  verbosity:
    required: false
    description: Control verbosity when running
    default: '1' # Some output
runs:
  using: node12
  main: main/index.js
